version: "2.1"
      
services:
  redis:
    image: redis:alpine
    networks:
      - fexum

  postgres:
    image: healthcheck/postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - fexum

  queue:
    image: rabbitmq:latest
    networks:
      - fexum

  web_wsgi:
    build: .
    depends_on:
      queue:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - fexum
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: gunicorn fexum.wsgi:application --bind 0.0.0.0:8001 --log-level=DEBUG --timeout 200
    environment:
      DJANGO_SETTINGS_MODULE: fexum.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  web_worker:
    build: .
    depends_on:
      queue:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - fexum
    volumes:
      - .:/code
    command: python manage.py runworker -v 2
    environment:
      DJANGO_SETTINGS_MODULE: fexum.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  web_asgi:
    build: ./
    depends_on:
      queue:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - fexum
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: fexum.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  worker:
    build: ./
    depends_on:
      queue:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - fexum
    volumes:
      - .:/code
    command: "celery -A fexum worker --beat --loglevel=info"
    shm_size: 8g
    environment:
      DJANGO_SETTINGS_MODULE: fexum.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  flower:
    build: ./
    depends_on:
      - queue
      - web_worker
      - web_asgi
    networks:
      - fexum
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    command: "celery flower -A fexum --address=0.0.0.0"
    environment:
      DJANGO_SETTINGS_MODULE: fexum.settings
      HOST: "*"
      DEBUG: "False"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  nginx:
    build: ./deployment
    networks:
      - fexum
    depends_on:
      - web_wsgi
      - web_asgi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./media:/media
    environment:
      NGINX_HOST: 0.0.0.0
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /setup/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  fexum:
