version: "2"
      
services:
  redis:
    image: redis:alpine
    networks:
      - predots

  postgres:
    image: postgres:9.4
    networks:
      - predots

  queue:
    image: rabbitmq:latest
    networks:
      - predots

  web:
    build: .
    depends_on:
      - queue
      - redis
      - postgres
    networks:
      - predots
    volumes:
      - .:/code
    command: python manage.py runworker -v 2
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  web_asgi:
    build: ./
    depends_on:
      - postgres
      - redis
      - queue
    networks:
      - predots
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  worker:
    build: ./
    depends_on:
      - queue
      - postgres
      - redis
    networks:
      - predots
    volumes:
      - .:/code
    command: "celery worker --app=predots"
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  flower:
    build: ./
    depends_on:
      - queue
      - web
      - web_asgi
    networks:
      - predots
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    command: "celery flower -A predots --address=0.0.0.0"
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "True"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

networks:
  predots:
