version: "2"
      
services:
  redis:
    image: redis:alpine
    networks:
      - predots

  postgres:
    image: postgres:9.4
    networks:
      - predots

  queue:
    image: rabbitmq:latest
    networks:
      - predots

  web_wsgi:
    build: .
    depends_on:
      - queue
      - redis
      - postgres
    networks:
      - predots
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: gunicorn predots.wsgi:application --bind 0.0.0.0:8001 --log-level=DEBUG --timeout 200
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "False"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  web_worker:
    build: .
    depends_on:
      - queue
      - redis
      - postgres
    networks:
      - predots
    volumes:
      - .:/code
    command: python manage.py runworker -v 2
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "False"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  web_asgi:
    build: ./
    depends_on:
      - postgres
      - redis
      - queue
    networks:
      - predots
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "False"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  worker:
    build: ./
    depends_on:
      - queue
      - postgres
      - redis
    networks:
      - predots
    volumes:
      - .:/code
    command: "celery worker --app=predots --loglevel=INFO"
    shm_size: 8g
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "False"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  flower:
    build: ./
    depends_on:
      - queue
      - web_worker
      - web_asgi
    networks:
      - predots
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    command: "celery flower -A predots --address=0.0.0.0"
    environment:
      DJANGO_SETTINGS_MODULE: predots.settings
      HOST: "*"
      DEBUG: "False"
      SECRET_KEY: "WKjWB3905LW3i1TAFUYE4Ve2JGiI5Ebt"

  nginx:
    build: ./deployment
    networks:
      - predots
    depends_on:
      - web_wsgi
      - web_asgi
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: 0.0.0.0
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /setup/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  predots:
