# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relevancy',
            unique_together=set([]),
        ),
    ]
