# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_rarresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('error', 'Error'), ('done', 'Done')], default='processing', max_length=10),
        ),
    ]
