# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20170308_1211'),
        ('features', '0003_auto_20170308_1356'),
    ]

    operations = [
    ]
