# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.FloatField()),
                ('to_value', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='RarResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevancy', models.FloatField()),
                ('redundancy', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rar_results', to='features.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Dataset')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('significance', models.FloatField()),
                ('frequency', models.FloatField()),
                ('to_value', models.FloatField()),
                ('marginal_distribution', jsonfield.fields.JSONField(default=[])),
                ('conditional_distribution', jsonfield.fields.JSONField(default=[])),
                ('rar_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.RarResult')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'dataset', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='rarresult',
            unique_together=set([('target', 'feature', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('name', 'dataset')]),
        ),
    ]
