# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('to_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('relevancy', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('redundancy', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('rank', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_target', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('to_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('marginal_distribution', jsonfield.fields.JSONField()),
                ('conditional_distribution', jsonfield.fields.JSONField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
            ],
        ),
        migrations.AddField(
            model_name='bucket',
            name='histogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Histogram'),
        ),
    ]
