# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.FloatField()),
                ('to_value', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('processing', 'Processing'), ('in_memory', 'In Memory'), ('on_disk', 'ON Disk'), ('error', 'Error')], default='empty', max_length=10)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('is_categorical', models.NullBooleanField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Dataset')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RarResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Redundancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redundancy', models.FloatField()),
                ('weight', models.IntegerField()),
                ('first_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_features', to='features.Feature')),
                ('rar_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.RarResult')),
                ('second_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_features', to='features.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Relevancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevancy', models.FloatField()),
                ('rank', models.IntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='features.Feature')),
                ('rar_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.RarResult')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('order', models.IntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('frequency', models.FloatField()),
                ('to_value', models.FloatField()),
                ('marginal_distribution', jsonfield.fields.JSONField(default=[])),
                ('conditional_distribution', jsonfield.fields.JSONField(default=[])),
                ('relevancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Relevancy')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bin',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature'),
        ),
        migrations.AlterUniqueTogether(
            name='relevancy',
            unique_together=set([('feature', 'rank', 'rar_result')]),
        ),
        migrations.AlterUniqueTogether(
            name='redundancy',
            unique_together=set([('first_feature', 'second_feature', 'rar_result')]),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('name', 'dataset')]),
        ),
    ]
