# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'dataset')]),
        ),
    ]
