# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('default_hics', 'Default HiCS'), ('fixed_features_hics', 'HiCS with fixed features'), ('feature_set_hics', 'HiCS with feature set')], default='empty', max_length=30),
        ),
    ]
