# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
