# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20170105_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slice',
            old_name='score',
            new_name='deviation',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='score',
        ),
        migrations.AddField(
            model_name='slice',
            name='frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='significance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
