# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20170121_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([]),
        ),
    ]
