# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20170420_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='status',
        ),
        migrations.AddField(
            model_name='calculation',
            name='current_iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='max_iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('default_hics', 'Default HiCS'), ('random_feature_set_hics', 'HiCS on random feature set'), ('fixed_feature_set_hics', 'HiCS with fixed feature set'), ('feature_super_set_hics', 'HiCS with super set of given feature set')], default='none', max_length=30),
        ),
    ]
