# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20170510_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='current_iterations',
            new_name='current_iteration',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='max_iterations',
            new_name='max_iteration',
        ),
    ]
