# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20170510_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='feature',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
