# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_currentexperiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='analysis_selection',
            field=models.ManyToManyField(related_name='analysis_selection', to='features.Feature'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='visibility_blacklist',
            field=models.ManyToManyField(related_name='visibility_blacklist', to='features.Feature'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='visibility_rank_filter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='visibility_text_filter',
            field=models.CharField(default='', max_length=150),
        ),
    ]
