# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_experiment_visibility_exclude_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='visibility_exclude_filter',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='visibility_text_filter',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
