# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20170601_1126'),
        ('features', '0008_auto_20170613_1122'),
    ]

    operations = [
    ]
