# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-30 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_merge_20170613_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='features',
            field=models.ManyToManyField(blank=True, to='features.Feature'),
        ),
    ]
