# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-29 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20170528_1725'),
        ('features', '0009_merge_20170613_1205'),
    ]

    operations = [
    ]
