# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_merge_20170629_0956'),
        ('features', '0010_calculation_features'),
    ]

    operations = [
    ]
